blueprint:
  name: Automaticaly turn off light at night after delay
  description: Turn off a light at night after delay
  domain: automation
  source_url: https://github.com/maximerauch/homeassistant-blueprints/blob/main/auto_turn_off_light_at_night.yaml
  author: Maxime RAUCH

  input:
    light_target:
      name: Light or Switch
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    start_time:
      name: Start Time
      description: Start of the active time window (e.g., 23:00)
      default: "23:00:00"
      selector:
        time: {}

    end_time:
      name: End Time
      description: End of the active time window (e.g., 06:00)
      default: "06:00:00"
      selector:
        time: {}

    wait_time:
      name: Wait time
      description: Duration to leave the light on
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

triggers:
  - type: turned_on
    entity_id: !input light_target
    for:
      hours: 0
      minutes: 0
      seconds: !input wait_time
      
conditions:
  - condition: time
    after: !input start_time
    before: !input end_time
      
actions:
  - type: turn_off
    entity_id: light_target 
    
mode: restart
